apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my.fullname" . }}-secret
  labels:
    {{- include "my.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.config.database.user | b64enc }}
  DB_PASSWORD: {{ .Values.config.database.password | b64enc }}
